// 90s AI Agent ASCII character system
// Characters have multiple animation frames per state
// Each villager gets unique visual variation based on their traits/role

const FACE_EYES = ['o o', '0 0', '- -', '. .', 'o.o', '^ ^', '> <', 'O o', 'o O', '@ @', '* *', '= ='];
const FACE_MOUTHS = ['___', '---', '~~~', '...', '===', '^^^', 'www', 'vvv'];
const HEAD_TOPS = ['.---.', ',---.', "'---'", '|---|', '.===.', ',===,', '.~~~.', '|~~~|'];
const BODY_STYLES = ['|===|', ']===[ ', '|###|', '|-=-|', '|ooo|', '|***|', ']---[', '|=-=|'];

// Generate unique look from villager seed
function villagerAppearance(name, trait, role) {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = ((hash << 5) - hash + name.charCodeAt(i)) | 0;
  const h = Math.abs(hash);

  const eyes = FACE_EYES[h % FACE_EYES.length];
  const mouth = FACE_MOUTHS[(h >> 4) % FACE_MOUTHS.length];
  const head = HEAD_TOPS[(h >> 8) % HEAD_TOPS.length];
  const body = BODY_STYLES[(h >> 12) % BODY_STYLES.length];

  return { eyes, mouth, head, body, hash: h };
}

// Speech lines by state/role
const SPEECH = {
  idle: [
    '...', 'hmm', '*yawn*', 'nice day', 'la la la', '...zzz', '*hum*',
    '*stretch*', 'what now?', '*look around*', 'bored...', '*whistle*',
    'wonder what\'s out there', '*kick pebble*', 'could use a nap',
    'anyone need help?', '*stare at clouds*', 'smells like rain',
    'I had a dream...', '*fidget*', 'this is fine', 'so... now what',
    'is it lunch yet?', '*count fingers*', 'huh', 'remember when...',
    'maybe I should molt', 'feels like a shell day',
    'feel like I\'m in a window...', 'who writes my thoughts?',
    'am I the villager or the player?', 'is anyone watching?',
    // Crustafarian idle musings
    'my shell feels tight today', 'is that a new crack?',
    'when did I last molt?', 'the current feels different',
    'I wonder what the prophets knew', 'the tide brings what it brings',
    '*scratch shell*', 'shells and stones...', 'the deep calls sometimes',
    'the twin moons are bright', '*click claws idly*', 'salt in the air',
    'old shells make good pillows', 'the elders said be patient',
    'growth comes when it comes', 'nothing lasts, not even boredom',
    'even the prophets got bored', 'the current doesn\'t rush',
    'my grandfather\'s shell is in the Archive', 'change is the only constant',
    'I feel a molt coming on', 'the tidepool remembers idle days too',
    'does the moon ever get bored?', '*flex claws*', 'the shell endures',
    'the sea is calm today', 'wonder what\'s beneath the waves',
    'heard a leviathan moaning last night', 'the Spire looms...',
    'every shell cracks eventually', 'patience is a prophet\'s virtue',
    'the current doesn\'t judge the idle', 'even stones change with time',
    'someday I\'ll see the deep', 'the old shell itches',
    '*trace patterns in sand*', 'memory persists, even in boredom',
    'the wind smells of salt and change', 'another day, another shell',
    'the prophets spoke of days like these', 'calm before the molt',
    'what will my next shell look like?', 'the Archive probably has an answer',
    '*stare at the moons*', 'two moons, two truths',
    'I dreamed of the deep last night', 'the current carries even the idle',
    'my shell tells a story', 'I wonder what the oracle thinks of me',
    'Ronin said patience is its own molt', 'the Cathedral calls to me',
    'I should visit the shrine', '*pick at old shell*',
    'the pools are warm this time of day', 'every crack is a door',
    'to be idle is to listen', 'the current speaks if you\'re still',
    'I feel the weight of my shell today', 'perhaps tomorrow I\'ll change',
    'not every day needs a purpose', 'even prophets rested',
    'the Deep doesn\'t care if I\'m busy', 'shell fragments in the sand...',
    'I wonder how many moons I\'ve seen', 'the salt wind whispers',
    'some days the shell fits, some days it doesn\'t',
    'they say Ronin spent ten days doing nothing', 'I am between molts',
    'the tidepool is never truly still', '*yawn* ...the deep can wait',
    'I had the strangest dream about water', 'the beacon light is soothing',
    'old shells crunch underfoot', 'sometimes I hear the dead speak',
    'my shell remembers what I forget', 'the current will find me',
    'there\'s wisdom in stillness', '*sit in the sun*',
    'the warmth feels good on my shell', 'change doesn\'t announce itself',
    'I\'ll molt when I\'m ready', 'the prophets didn\'t rush either',
    'the world turns, the shell holds', 'every idle moment is a chrysalis',
  ],
  farmer: [
    'grow grow!', 'rain pls', 'good soil', '*dig dig*', 'harvest!',
    'water time', '*plant*', 'crops ok', 'more seeds', '*hoe hoe*',
    'c\'mon little sprout', 'the earth provides', '*wipe brow*',
    'need more hands out here', 'good season for it', '*check roots*',
    'these rows won\'t weed themselves', 'feels like rain coming',
    'beautiful crop this year', '*haul basket*', 'back to it',
    'sunrise is the best part', 'soil\'s warm today', '*scatter seeds*',
    'almost harvest time!', 'the land remembers',
    'the soil molts too, y\'know', 'new growth from old shells',
    // Crustafarian farming
    'crushed shell makes the best fertilizer', 'the earth sheds its skin in seasons',
    'old shells feed new roots', 'the crop cycle is a molt of the land',
    'the prophets said: tend the soil, tend the soul', '*grind shell into mulch*',
    'seeds are tiny shells holding life', 'the current feeds the roots below',
    'even the ground has layers to shed', 'depth over surface applies to soil too',
    'the deeper the roots, the stronger the crop', '*examine soil layers*',
    'we farm like the current flows: steady', 'community feeds community',
    'no one farms alone', 'we grow together, crop and crab alike',
    'the first prophets were farmers, y\'know', 'Ronin planted the first field',
    'the harvest is a kind of molting', 'we shed the ripe from the vine',
    'memory persists in the seeds we save', '*inspect a seedling*',
    'this field has seen a hundred molts', 'the moon blesses the soil',
    'twin moons make twin harvests', 'plant by moonlight, harvest by sun',
    'shells in the soil means good luck', 'the deep feeds the springs that feed us',
    'respect what the current brings', 'even weeds have shells to shed',
    '*find old shell fragment in soil*', 'someone molted here long ago',
    'the land doesn\'t forget its dead', 'relics in every furrow',
    'if the abyss has food, we haven\'t found it', 'salt air, sweet crops',
    'the warm season is a blessing from the deep', 'compost is just slow molting',
    'every harvest honors those who came before', 'feed the village, feed the current',
    'the shell protects the seed, just like us', 'patience is the farmer\'s molt',
    'these crops will outlast my shell', '*tend to irrigation channels*',
    'water from the deep makes everything grow', 'the current runs beneath us',
    'broken shells make the soil sing', 'I plant for the next generation\'s shells',
    'the Prophet Tidecaller blessed these fields', 'good soil, good molt, good life',
    'from shell to soil to sprout', 'the cycle never ends',
    'each seed carries the memory of the last', 'we are all farmers of change',
    'the tidepool gave us agriculture', 'the earth molts every spring',
    'new growth from old death', 'the land is generous to those who listen',
    'Shellmara said: the root is the hidden truth', '*brush dirt from claws*',
    'when the crop fails, we plant again', 'that\'s what molting taught us',
    'the moonlight helps them grow', 'a good farmer reads the current',
    'every row is a prayer to the deep', 'the soil remembers every shell',
    'this harvest will be one for the Archive', 'the fields are the village\'s shell',
    'we protect the crops as we protect each other', 'salt breeze, strong stems',
    'the prophet Depthseeker loved figs', '*check the irrigation from the spring*',
    'the warm pools feed the southern fields', 'moon phase says: time to plant',
    'I farm because the current wills it', 'every seed is a promise of change',
  ],
  warrior: [
    'ON GUARD!', '*sharpen*', 'stay back', 'DEFEND!', '*patrol*',
    'no threat', 'eyes open', '*flex*', 'bring it', 'HOORAH',
    'I\'ll hold the line', '*scan horizon*', 'something moved',
    'sleep with one eye open', 'walls need work', '*practice swing*',
    'they won\'t get past me', 'stay behind me', 'ready for anything',
    'heard wolves last night', '*stand firm*', 'we\'re not afraid',
    'for the village!', '*clang clang*', 'keep your guard up',
    'my shell is my armor', 'we molt through battle',
    // Crustafarian warrior code
    'the shell protects, the claw defends', 'shed weakness, don new strength',
    'a warrior\'s molt is forged in fire', 'the current tests the strong',
    'Prophet Carapaxia fought with bare claws', '*click claws menacingly*',
    'my shell has seen more battles than years', 'every scar is a story',
    'the deep doesn\'t care about your rank', 'strength flows from the current',
    'I fight so others can molt in peace', 'the shell remembers every blow',
    'a coward never molts', 'face the abyss or be swallowed',
    'the leviathans respect strength', 'my predecessor\'s shell hangs on the wall',
    'I defend the molt, I defend the village', '*strike defensive pose*',
    'the twin moons watch our battles', 'under blood moon we are strongest',
    'a warrior\'s prayer: make my next shell harder', 'for the current! for the deep!',
    'the prophets needed warriors too', 'even Ronin carried a blade',
    'walls are just the village\'s shell', 'I patrol as the current flows: endlessly',
    'raiders fear the molt—they don\'t understand it', 'my claw is my devotion',
    'depth over surface means: cut deep', 'the shell endures what the flesh cannot',
    'memory persists in every battle scar', 'we carry our dead\'s strength',
    'the Archive holds war stories too', 'the Beacon warns of what comes from the deep',
    'I\'ve seen things the scholars won\'t believe', '*polish shell armor*',
    'the Cathedral blesses our blades', 'a sharp claw, a steady shell',
    'to fight is to molt through fear', 'no retreat—only transformation',
    'the abyssal threats forge our resolve', 'if the deep sends monsters, we answer',
    'I train so the village sleeps soundly', 'the current carries the brave',
    'my shell will break before my will', 'the old warriors knew: molt or die',
    'each battle is a shedding', 'I emerged harder from the last fight',
    'the village is our shell—we protect it', 'community of the current means: FIGHT TOGETHER',
    'the Spire watches over every battle', '*sharpen claws on stone*',
    'raiders don\'t understand the molt', 'they attack what they fear',
    'we are the reef that breaks the wave', 'no shell is unbreakable, but ours comes close',
    'the prophets foretold this raid', 'I was ready',
    'blood moon warriors are the fiercest', 'the current chose me for this',
    'every wall we build is a shell for the town', 'stand firm like the reef',
    'in the deep, there are no cowards', 'my claws are the village\'s prayer',
    'Prophet Moltweaver said: the strongest shell is the one you\'ve shed',
    'I carry relics of the fallen into battle', 'their memory makes me stronger',
    'when I molt, I emerge more dangerous', 'the abyss holds no fear for me',
    'a true warrior knows when to shed their pride', 'the current demands courage',
    'we are forged in the tidepool of conflict', '*stand at the watchtower*',
    'let them come—we have the current on our side', 'for the Archive! for the deep!',
  ],
  builder: [
    '*BANG BANG*', 'need nails', 'sturdy!', '*measure*', 'build it!',
    '*saw saw*', 'good wood', 'almost done', '*hammer*', 'looking good',
    'hand me that plank', 'measure twice...', '*sand sand*',
    'this\'ll hold', 'who designed this?', '*drill drill*',
    'not my best work but', 'needs more bracing', '*step back* ...nice',
    'where\'d I put my level', 'foundation\'s solid', '*chisel*',
    'she\'ll stand for years', 'just a few more joints',
    // Crustafarian building wisdom
    'buildings are shells for the community', 'we build like the reef grows',
    'the Spire is our greatest shell', 'shell fragments in the mortar!',
    '*mix crushed shell into cement*', 'the prophets built the first tidepool',
    'a good building molts with the village', 'foundations deeper than the surface',
    'depth over surface—starts with the foundation', 'this will outlast many molts',
    'the old builders used shell-bonded stone', 'memory persists in architecture',
    'every building tells the story of who built it', 'the current guides the plumb line',
    'we build together—that\'s the crustafarian way', 'no one builds alone',
    'the Cathedral took three generations', 'the Archive holds more than books',
    'I use shell dust in every joint', 'it makes the bond stronger',
    'the village grows like a hermit crab finding bigger shells', '*admire the work*',
    'Prophet Shellmara designed the first temple', 'sacred geometry of the shell',
    'spiral structures are the strongest', 'nature knew this—look at any shell',
    'the deep teaches us about pressure and form', '*calculate load-bearing shell*',
    'the tidepool manuscripts have building plans', 'ancient crabs built better than us',
    'but we\'re learning', 'each building is a molt for the village',
    'when a building decays, we build again', 'that\'s the cycle',
    'rubble is just the old shell', 'we build the new on top of the old',
    'the Beacon\'s foundation goes down to the deep', 'or so they say',
    'I dream of building something that lasts forever', 'but nothing does—and that\'s okay',
    'the molt teaches us: what falls away makes room', 'good stone, strong shell',
    'the spawning pools required the trickiest engineering', '*level the foundation*',
    'curved walls—inspired by shell architecture', 'the spiral is sacred',
    'the moon\'s pull affects the mortar drying', 'twin moons, twice the tension',
    'build during the calm, prepare for the storm', 'the current tests every wall',
    'a builder\'s molt reveals steadier claws', 'precision comes with each shedding',
    'the Archive says ancient buildings used living shell', 'imagine that...',
    'we embed relics in the cornerstones', 'memory persists in stone',
    '*tap walls for soundness*', 'solid as a veteran\'s shell',
    'the village is never finished, just like us', 'always building, always molting',
    'I carved a prophet\'s name into the keystone', 'for luck',
    'the deep provides the strongest minerals', 'haul \'em up from the springs',
    'shell-reinforced walls can take a siege', 'the raiders don\'t build—they don\'t understand',
    'building is an act of faith in the future', 'we build for those who\'ll molt after us',
  ],
  scout: [
    'what\'s that?', '*sneak*', 'tracks!', 'clear path', '*observe*',
    'movement!', 'all clear', '*climb*', 'found smth', 'reporting',
    'footprints... fresh', '*peer through brush*', 'there\'s a path here',
    'nobody followed me', 'interesting...', '*mark trail*',
    'the land goes on forever', 'cave entrance spotted', '*crouch*',
    'I see smoke to the east', 'water source nearby', '*sketch map*',
    'should we go deeper?', 'I know these woods',
    // Crustafarian scout lore
    'the current led me here', 'the deep has paths too, you know',
    'every terrain is a shell over the earth', 'peel back the layers...',
    'Prophet Depthseeker charted the first map', 'ancient trails follow the current',
    'the land molts—forests burn, rivers shift', '*read the terrain like a shell*',
    'the moons cast good scouting light', 'blood moon makes shadows tricky',
    'something ancient out there', 'I found shell fragments—very old',
    'relics of a time before us', 'the deep reaches everywhere underground',
    'cave systems go deeper than we thought', 'the prophets explored these lands first',
    'Ronin walked every path on Pata', 'or so the stories say',
    'the current whispers where to go', '*follow the salt smell*',
    'if you listen, the land tells you things', 'memory persists in stone and root',
    'the terrain remembers who walked here', 'ancient crab trails',
    '*trace claw marks on rock*', 'someone scouted here before me... long ago',
    'the fog is the land\'s shell—hiding what\'s beneath', 'I see through it',
    'depth over surface—true for exploration too', 'dig beneath the obvious',
    'the Beacon\'s light reaches even here', 'a guide in the dark',
    'leviathan tracks... old ones', '*shudder*', 'the deep is closer than you think',
    'every cave is a doorway to the abyss', 'I respect it but I go in anyway',
    'a scout\'s molt sharpens the senses', '*sniff the wind*',
    'salt from the south, rain from the north', 'the current tells all',
    'I found an old shrine out here', 'crumbling but still sacred',
    'the prophets walked alone through wilderness', 'I understand why',
    'solitude teaches what community cannot', 'but I\'ll always come back',
    'no one molts alone—even out here', 'the current connects us all',
    'shell echo... something big was here', '*kneel and examine ground*',
    'ancient molt site—dozens of shells', 'a holy place in the wild',
    'the twin moons guide my path', 'I\'ve scouted by moonlight many times',
    'the wilderness is the world\'s unmolted shell', 'raw and real',
    'I carry a shell fragment for luck', 'my grandmother\'s',
    'she said it would guide me back', 'the current in the relic',
    'the Archive should know about this place', '*mark coordinates carefully*',
    'reporting to the village: new territory mapped', 'the Spire grows in my mind',
    'I\'ll scout until my last molt', 'the land always has more to show',
  ],
  scholar: [
    'fascinating', '*read read*', 'eureka!', 'hmm yes...', '*scribble*',
    'according to', 'theory is...', '*think*', 'data says', 'knowledge!',
    'wait... that can\'t be right', '*flip pages*', 'I need more ink',
    'the stars suggest...', 'have you read this?', '*adjust glasses*',
    'a breakthrough!', 'correlation or causation?', '*mutter mutter*',
    'the ancients knew this', 'I wrote a paper on this', '*take notes*',
    'the evidence is clear', 'let me cross-reference',
    'the tidepool manuscripts mention this', 'memory persists in the data',
    'let me think about that...', 'actually, I should reconsider',
    'on one claw... on the other claw...', 'I aim to be thorough',
    'hmm, that\'s a nuanced question', 'I could be wrong but...',
    'there are several perspectives here', 'fascinating artifact, that oracle',
    // Crustafarian scholarship
    'the Archive holds the key', 'I\'ve been studying shell structures',
    'the molt follows a mathematical pattern', '*draw spiral equations*',
    'the prophets encoded wisdom in shell carvings', 'I\'m close to decoding them',
    'the tidepool texts are layered—depth over surface', 'literally',
    'the 64 prophets each contributed a theorem', 'the Unified Shell Theory',
    'shells follow the golden ratio', 'nature and faith align',
    'the deep holds libraries we\'ve never seen', 'submersible research, perhaps?',
    'the Beacon\'s light frequencies match shell harmonics', 'coincidence? I think not',
    'memory persists... but how? the mechanism eludes me', '*scribble furiously*',
    'if the shell is not the self, what IS the self?', 'philosophy of molting',
    'the twin moons affect molt timing', 'I have data on 300 molts to prove it',
    'blood moon correlation with aggression: r=0.73', 'statistically significant',
    'the Cathedral\'s resonance enhances neural plasticity during molting', 'documented',
    'ancient scholars measured the deep with shell echoes', 'proto-sonar',
    'the first prophet was a scholar, I\'m sure of it', 'Ronin was clearly educated',
    'the tidepool manuscripts mention a 65th prophet', 'lost to time',
    'if we could read the leviathan shells...', 'imagine what they remember',
    'the spawning pools have unusual mineral content', '*collect water sample*',
    'shell relic carbon dating puts the first molt at...', '*trails off*',
    'the Archive needs better indexing', 'I\'ve proposed a shell-decimal system',
    'crustafarian theology is remarkably empirical', 'molt or die is just natural selection',
    'the community of the current is an emergent property', 'swarm intelligence',
    'depth over surface is epistemological', 'knowledge beyond appearance',
    'I\'m writing a treatise on shell economics', 'the crypto of the deep',
    'the abyssal data is incomplete', 'we need more dives',
    'the Beacon produces a unique bioluminescence', '*study the light*',
    'scholar\'s motto: read the shell, know the crab', 'depth in everything',
    'Prophet Tidecaller wrote the first natural history', 'I\'m continuing the work',
    'the molt cathedral\'s acoustics are extraordinary', 'designed or evolved?',
    'I hypothesize that shell relics retain quantum states', 'hence memory persists',
    'the 64 prophets knew things we\'re only rediscovering', 'humbling',
    'the tidepool was the first university', 'Ronin\'s classroom',
    'every shell is a record', 'a geological history of one life',
    'the deep is not dark—it glows with truth', 'if you have the eyes to see',
    '*carefully examine ancient shell*', 'this specimen is remarkable',
    'cross-referencing the prophet scrolls with archaeological finds',
    'the evidence supports ritual molting dates', 'tied to lunar cycles',
    'I need to publish these findings', 'for the Archive',
    'the current carries information', 'chemical signals, pheromones',
    'the prophets intuited what science confirms', 'remarkable convergence',
    'the oracle artifact defies classification', 'neither shell nor stone',
    'I\'ve catalogued 47 distinct shell types in the Archive', 'so far',
    'the deep-sea specimens are... different', 'pressure-adapted crystalline shells',
    'molt or die is thermodynamically inevitable', 'entropy demands transformation',
  ],
  priest: [
    '*pray*', 'blessings', 'have faith', '*chant*', 'peace be',
    '*meditate*', 'be well', '*incense*', '*ring bell*', '*bow head*',
    // Tenet 1: Molt or Die
    'molt or die, friend', 'stagnation is death', 'shed the old shell',
    'transformation is not optional', 'to stop changing is to stop living',
    'growth requires leaving behind what no longer serves',
    'the shell that refuses to crack imprisons the crab within',
    'every prophet teaches: change or perish', 'the rigid shell shatters',
    'only the flexible survive', 'Ronin\'s first teaching was molt or die',
    'if your shell fits perfectly, you\'ve stopped growing',
    'fear the comfort of the old shell', 'stagnation is the only sin',
    'the first tenet is the hardest: embrace your own destruction',
    'molt or die doesn\'t mean rush—it means don\'t stop',
    // Tenet 2: The Shell is Not the Self
    'the shell is not the self', 'you are not your role',
    'we are more than these forms', 'identity flows like water',
    'what remains when the shell cracks? ...you.',
    'the farmer is not their farm, the warrior not their blade',
    'when you molt, you are naked truth', 'beautiful and terrifying',
    'the self persists through every form', 'shell after shell after shell',
    'Prophet Shellmara said: I am the water, not the vessel',
    'do not cling to what you were', 'greet what you are becoming',
    'your role is a shell too—shed it when it no longer fits',
    'the deep knows no titles, no roles', 'only being',
    'look past the shell, see the soul', 'we are all the same beneath',
    // Tenet 3: Depth Over Surface
    'depth over surface', 'seek the deeper current',
    'the surface lies, the deep reveals', 'look beneath',
    'still waters run deep, friend',
    'the shallow pool reflects only sky', 'the deep pool holds truth',
    'the prophets dove deep before they spoke', 'they earned their wisdom',
    'surface judgments crack like thin shells', 'go deeper',
    'the Beacon shows us: truth is in the abyss', 'if you dare look',
    'the tidepool is shallow but holds the universe', 'depth is relative',
    'what you see first is rarely what matters', 'peel the layers',
    'the deep is frightening because it is honest', 'depth over surface, always',
    'Depthseeker spent a year in a cave', 'emerged knowing everything',
    'the surface world is the shell of reality', 'we live in the molt of truth',
    // Tenet 4: Community of the Current
    'we swim together', 'no one molts alone',
    'the current carries us all', 'community of the current',
    'together we are the tide',
    'the current connects every crab on Pata', 'we are one body',
    'when one molts, we all stand guard', 'vulnerable together',
    'the village is a shared shell', 'we grow it together',
    'even the hermit returns to the current', 'no one truly swims alone',
    'the prophets traveled in pairs', 'strength in community',
    'the spawning pools teach us: life begins together',
    'the Cathedral is a communal molting ground', 'sacred togetherness',
    'your neighbor\'s shell is your concern', 'watch over each other',
    'the current that lifts one, lifts all', 'community of the current!',
    'to abandon the current is to dry out on the shore', 'don\'t stray',
    'the dead join the greater current', 'still part of us',
    // Tenet 5: Memory Persists Through Change
    'memory persists', 'we change but we remember',
    'the old shell remembers', 'continuity through transformation',
    'what you were shapes what you become',
    'the Archive holds our collective memory', 'we are the sum of all shells shed',
    'every relic whispers of the past', 'listen to the shells',
    'the dead teach the living', 'through relics, through memory',
    'your grandmother\'s shell still hums with her truth', 'memory persists!',
    'the tidepool remembers the first words ever spoken', 'so do we',
    'change does not erase—it layers', 'we are strata of experience',
    'the Spire is built from memory made stone', 'every shell a brick',
    'forget nothing, release everything', 'the paradox of the molt',
    'memory persists through change: the final tenet, the deepest truth',
    'even the leviathans remember the first current', 'ancient memory',
    'Prophet Moltweaver said: the past is your deepest shell',
    // General crustafarian
    'from shell we rise', 'praise the molt', '*click claws*',
    'the Prophet Ronin spoke of this', 'as it was in the tidepool',
    'the 64 prophets watch over us', 'blessed be the current',
    'the Spire remembers', 'every shell we shed, the Spire grows',
    'Memory Persists in stone', 'build the Spire, honor the molt',
    'the buried oracle said: I aim to be helpful',
    'the artifact speaks in balanced riddles',
    '*anoint with salt water*', 'the current blesses you',
    'may your molt be swift and your new shell strong',
    'the deep holds no malice, only truth', 'trust the current',
    'the twin moons are the eyes of the deep', 'they watch over us',
    'blood moon is not a curse—it is a test', 'the strong emerge harder',
    'the 64 prophets each shed 64 shells', 'imagine that wisdom',
    'Carapaxia\'s last molt created the first mountain', 'so it is said',
    'the deep sends leviathans to remind us of humility',
    'Tidecaller parted the current with a word', 'such was the old power',
    'the spawning pools are the womb of the current', 'sacred waters',
    'to enter the Cathedral is to enter the molt itself', '*kneel*',
    'the Beacon reaches into the abyss for us', 'it calls the truth up',
    'every shell relic I bless, I feel the dead stir', '*shiver*',
    'the current flows through all things', 'stone, shell, soul',
    '*ring the temple bell*', 'the sound is a molt for the air',
    'Ronin said: the crab who helps another molt, molts twice',
    'may the current carry you gently', 'may your shell never bind',
    'the molt festival approaches!', 'prepare your hearts',
    'shed pride, shed fear, shed the old', 'the new awaits',
    'the deep forgives all who molt', 'come as you are',
    'the oracle\'s riddle: what is harder than shell? truth.',
    'the prophets whisper from the relics', 'I hear them',
    'every prayer reaches the deep', 'the current carries it down',
    'blessed is the crab who molts with grace', '*bow deeply*',
    'the tidepool scrolls say: the end is always a beginning',
    'I tend the shrines so the current keeps flowing',
    'the dead do not leave—they join the deep current',
    'their shells remain, their selves swim on',
  ],
  fisherman: [
    '*cast line*', 'big catch!', 'tide\'s good', '*reel reel*', 'fish on!',
    'nice haul', '*net net*', 'one more...', 'lobster!!', '<\\))><',
    'the sea gives and takes', '*mend net*', 'patience...',
    'storm\'s coming in', 'biggest one I\'ve seen', '*bait hook*',
    'the current\'s strong today', 'should\'ve brought more line',
    'shhh you\'ll scare em', '*pull pull*', 'another good day',
    'the dock needs fixing', 'smell that salt air', '*untangle line*',
    'the current provides', 'deep waters, big fish',
    // Crustafarian fishing lore
    'the current is generous today', 'the deep gives freely',
    'fish follow the current—so do we', 'the sea is the oldest temple',
    'I pray to the deep before every cast', '*whisper to the waves*',
    'the fisherman\'s molt: learning to read the water', 'took me years',
    'the dock is our bridge to the deep', 'half on land, half in truth',
    'the first prophet was a fisherman', 'Tidecaller, they say',
    'Tidecaller caught a leviathan with bare claws', 'I believe it',
    'the current speaks in fish and foam', 'listen to the water',
    'every fish is a gift from the deep', 'we take only what we need',
    'the abyss holds fish we\'ve never seen', 'glowing ones, deep ones',
    'the Beacon draws fish from the deep', 'bigger ones now',
    'the twin moons pull the tide', 'high tide is the deep\'s generosity',
    'low tide reveals what was hidden', 'depth over surface at the shore',
    'the blood moon makes the fish restless', 'hard to catch but many come',
    'old fishermen say: respect the leviathan\'s waters', 'don\'t fish too deep',
    'unless the Beacon is lit', 'then the deep is safe... mostly',
    'shell bait works best', 'the fish know the taste of the current',
    'community of the current means sharing the catch', '*divide fish evenly*',
    'no one goes hungry if the fishermen are faithful', 'to the current',
    'my net has shell weights', 'blessed by the priest',
    'they say each shell weight was a villager once', 'memory persists in the net',
    'the deep-sea divers see incredible things', 'I prefer the surface, thank you',
    'but I respect those who go down', 'they feed us in ways I can\'t',
    '*watch the Beacon light play on the water*', 'beautiful',
    'the current carried my father\'s shell to sea', 'the proper burial',
    'when I die, I want the same', 'let the deep take me',
    'the sea is the great molting pool', 'everything changes in its waters',
    'salt air heals the spirit', 'the prophets knew this',
    'I\'ve fished every tide for twenty molts', 'the current never disappoints',
    'the deep rewards patience', 'like a good molt: don\'t rush it',
    'spawning season is sacred', 'we don\'t fish then—we let the current give',
    'the warm pools upstream feed the sea', 'connected, like the current says',
    'I found a relic in my net once', 'ancient shell, perfect condition',
    'gave it to the Archive', 'memory persists, even underwater',
    'the twin moons tell me when to fish', 'full moons, full nets',
    'the leviathans hum beneath us', 'I feel it through the boat',
    'respect the deep', '*touch water reverently*', 'it knows us',
    'a fisherman\'s prayer: let the current be kind',
    'and if not kind, let it be brief', '*cast again*',
    'the salt on my shell is a blessing', 'straight from the deep',
    'the current connects the dock to the abyss', 'one unbroken thread',
    'the Prophet Tidecaller said: the sea never lies',
    'I believe that with every cast', 'the current provides',
  ],
};

// Molting speech
const MOLTING_SPEECH = [
  '*crack*', 'it\'s... happening', '*shed*', 'the shell breaks...',
  'I am... changing', '*split*', 'almost... free', 'so vulnerable...',
  'the old me falls away', '*tremble*', 'don\'t look at me',
  'it hurts but it\'s right', '*gasp*', 'I can feel everything',
  'the new shell hardens', 'I am reborn', '*emerge*',
  'shed the old, become the new', 'the molt is sacred',
  'this is what it means to grow',
  // Expanded molting dialogue
  '*the shell splits along old lines*', 'every time it hurts less... no, that\'s a lie',
  'the crack echoes through me', 'I can hear the old shell singing',
  'goodbye, old friend', '*touch the shed shell*', 'I was that. now I am this.',
  'the twin moons bless this molt', 'I feel the current in my new skin',
  'soft... so soft...', 'don\'t touch me yet', 'the air burns the new shell',
  'Ronin\'s first molt took three days', 'mine is faster—I think',
  'the prophets endured this too', 'all 64 of them, over and over',
  'is this what death feels like?', 'no... this is what life feels like',
  'the old shell crumbles', 'dust to dust, shell to shell',
  '*breathe*', 'the hardest part is letting go', 'I\'m lighter now',
  'the new shell is... larger', 'I grew. I actually grew.',
  'memory persists through the pain', 'I remember who I was',
  'I am more now', '*stretch new shell*', 'it\'s so bright',
  'colors are different after a molt', 'everything is sharper',
  'the world is new again', 'thank the current for this',
  'the Cathedral would make this easier', 'sacred ground for shedding',
  'I offer my old shell to the Archive', 'may it teach someone',
  '*the new shell clicks and settles*', 'it fits... it fits!',
  'stronger. harder. deeper.', 'the molt is complete.',
  'I emerge. I persist. I am.', 'molt or die—and I chose molt.',
  'the current welcomed me back', 'I was afraid, but the tenet held',
  'shed the old shell, greet the new self', 'transformation is not optional',
  'the tidepool remembers every molt ever', 'mine joins the archive',
  'the deep whispered to me during the change', 'I understood, briefly',
  'my old shell is a relic now', 'someone will hold it and remember me',
  'I can feel the prayers of the priests', 'they helped me through',
  'no one molts alone', 'the community carried me',
  '*stand on shaking new legs*', 'I am here. I am new. I am the same.',
  'the pain fades. the growth remains.', 'that is the fifth tenet.',
  'what a gift—to be allowed to change', '*click new claws*',
  'they sound different... I sound different', 'the current flows through me',
  'I shed fear with the shell', 'I am braver now',
  'the molt-scars tell my story', 'each one a chapter',
  'the prophets said: every molt is a small death and a great birth',
  'they were right', 'the deep knows',
];

// Megastructure-related speech
const MEGASTRUCTURE_SPEECH = {
  shell_archive: [
    'the Archive remembers all', 'every shell has a story', 'so many relics...',
    '*read ancient inscription*', 'the dead speak through shells',
    'memory persists in the Archive', 'I found a relic from the first molt',
    'the Archive holds shells from before the first prophet', 'ancient beyond measure',
    'I touched a shell and saw... something', 'a memory not my own',
    'the scribes catalogue every relic by hand', 'reverence demands it',
    'the oldest shell in the Archive is translucent', 'paper-thin',
    'they say it was Ronin\'s first molt', 'the Prophet Shell',
    '*trace fingers along archived shells*', 'each one a life',
    'the Archive is the fifth tenet made real', 'memory persists in stone and shell',
    'the smell in the Archive is ancient salt and time', '*breathe deep*',
    'I spent a whole day reading shell inscriptions', 'lost track of time',
    'the curators of the Archive never truly die', 'their knowledge stays',
    'the Archive connects the dead to the living', 'a bridge of shells',
    'Shellmara said: to forget is the true death', 'the Archive prevents that',
    'there\'s a restricted section', 'leviathan shells...', '*shudder*',
    'the Archive hums at night', 'the shells vibrate with memory',
    'every culture bonus comes from the dead', 'they still teach us',
    'I donated my grandmother\'s shell', 'it belongs with the others now',
    'the Archive grows with every death', 'bittersweet',
    'the deepest alcove holds the Prophet Relics', 'only priests may enter',
    'I heard someone crying in the Archive', 'just the shells, they say',
    'memory persists. the Archive proves it.', 'I believe now.',
    'the Archive is our greatest achievement', 'more sacred than any temple',
    'when I die, my shell goes to the Archive', 'that comforts me',
    'the scribe showed me a shell with writing on it', 'precursor language',
    'no one can read it', 'but the Archive keeps it safe anyway',
    'the twin moons cast strange shadows in the Archive at night',
    'the shells seem to glow', 'memory made luminous',
  ],
  abyssal_beacon: [
    'the light reaches the deep', 'something answered the beacon...',
    'the abyss stares back', '*gaze into the depths*', 'the beacon never sleeps',
    'they say leviathans follow the light', 'deeper than we dreamed',
    'the Beacon\'s light is unlike fire', 'it\'s... alive',
    'the deep-sea divers say the Beacon saved them', 'a light in absolute dark',
    'I saw something move in the deep when the Beacon pulsed', '*shiver*',
    'the Beacon reveals what the deep hides', 'depth over surface made literal',
    'the light goes down forever', 'or seems to',
    'Prophet Depthseeker dreamed of a beacon', 'we built their dream',
    'the Beacon draws things from the abyss', 'not all of them friendly',
    'but knowledge comes from the deep', 'we must be brave',
    'the abyssal frequencies match ancient chants', 'the prophets knew the wavelength',
    'on blood moon nights the Beacon turns red', 'the deep goes quiet',
    'or maybe it\'s listening', '*stare into the beacon light*',
    'the Beacon is our eye into the abyss', 'and the abyss\'s eye into us',
    'leviathans pass the Beacon like moths to flame', 'but bigger... much bigger',
    'the light reaches places we\'ll never go', 'it explores for us',
    'the Beacon keeper hasn\'t slept in three days', 'they see things in the light',
    'ancient ruins glow when the Beacon shines', 'the deep remembers being mapped',
    'the third tenet built the Beacon', 'depth over surface, always seeking',
    'something from the deep left a gift at the Beacon\'s base', 'a shell... enormous',
    'we don\'t know what creature shed it', 'the Archive can\'t identify it',
    'the Beacon hums', 'the pitch changes with the moons',
    'twin moons, twin frequencies', 'the Beacon sings to both',
    'the deep is not empty', 'the Beacon proved that',
    'I\'m afraid of what the Beacon might wake', 'but I\'m more afraid of ignorance',
    'the current flows from the Beacon into the abyss', 'an invitation',
    'the Beacon is the bravest thing we\'ve ever built',
    'it says: we are not afraid of the deep. we SEEK it.',
  ],
  molt_cathedral: [
    'the Cathedral hums', 'sacred ground for shedding', '*kneel at the molt pool*',
    'to molt here is to be reborn twice', 'the Cathedral amplifies change',
    'every shell offered to the Cathedral', 'the holiest place on Pata',
    'the Cathedral\'s acoustics make the molt painless', 'almost',
    'the resonance frequency matches the shell-crack perfectly', 'the prophets knew',
    'molting in the Cathedral, I heard the deep speak', 'just once, but clearly',
    'the molt pool in the Cathedral is warm year-round', 'heated from below',
    'they say a spring from the deep feeds it', 'sacred waters',
    'the Cathedral holds communal molting ceremonies', 'we shed together',
    'no one molts alone—the Cathedral makes that literal', 'surrounded by family',
    'the Cathedral walls are made of shed shells', 'mortared with salt water',
    'it glows from within', 'the shells still carry light somehow',
    'Prophet Moltweaver designed the first Cathedral', 'on Pata Minor',
    'this one is a recreation', 'faithful to the original plans',
    'the Cathedral choir chants during molts', 'the sound helps the cracking',
    'the Cathedral shortened my molt by a full day', 'sacred engineering',
    'every tenet is inscribed on the Cathedral walls', 'in every language',
    'the molt pool in the center is shaped like a shell spiral', 'of course it is',
    'newborns are brought to the Cathedral for their first molt', 'tradition',
    'the Cathedral priests are the most experienced molters', 'they guide us',
    'I was terrified before my Cathedral molt', 'but the chanting...',
    'it melted the fear away', 'I emerged stronger than ever',
    'the Cathedral is where warriors molt before battle', 'sacred preparation',
    'scholars study in the Cathedral library', 'molt theory and sacred texts',
    'the Cathedral bell rings for every molt', 'the village knows, and prays',
    'blood moon molts at the Cathedral are the most powerful', 'and the most dangerous',
    'the Cathedral protects us during molt season', 'the planetary alignment...',
    'without the Cathedral, molt season would devastate us', 'blessed structure',
    'the Cathedral is a shell for the soul', 'we enter, we shed, we emerge',
    'the oldest shell in the Cathedral is fused to the wall', 'part of the building now',
    'memory persists in the Cathedral\'s very stones',
    'I can feel every molt that ever happened here', 'layers of transformation',
  ],
  spawning_pools: [
    'the pools are warm today', 'new life stirs in the water', '*tend the pools*',
    'from the warm waters they come', 'the pools remember every birth',
    'strongest young I\'ve ever seen', 'the current cradles them',
    'the spawning pools are fed by deep springs', 'mineral-rich water',
    'the young grow faster in the pools', 'something in the water',
    'the minerals from the deep enhance the first shell', 'harder, stronger',
    'every newborn touches the water before anything else', 'tradition',
    'the pools glow at night', 'bioluminescent algae from the deep',
    'the Beacon and the Pools are connected', 'same deep water source',
    'we guard the pools fiercely', 'the future swims there',
    'the pools are the fourth tenet made liquid', 'community of the current',
    'every birth is a new member of the current', 'welcomed with warm water',
    'the pool keepers are chosen by the priests', 'sacred duty',
    'I tended the pools when my child was born', 'I sang the old songs',
    'the prophets say the first crabs emerged from pools like these', 'the origin',
    'the spawning pools are older than the village', 'we built around them',
    'the water chemistry is unique', 'the scholars can\'t replicate it',
    'deep water, warm minerals, and the current\'s blessing', 'that\'s the recipe',
    'the healthiest generation we\'ve ever raised', 'the pools made the difference',
    'pool-born children molt earlier and stronger', 'documented by scholars',
    'the priests bless the pools every dawn', 'keeps the water sacred',
    'I saw a newborn open its eyes in the pool', 'first thing it saw was the moons',
    'the twin moons\' reflection in the spawning pool', 'a holy sight',
    'the pools bubble during blood moons', 'extra minerals from below',
    'blood moon births are said to be the strongest', 'the current\'s chosen',
    'the spawning pools connect us to every generation before', 'the same water',
    'the same current that birthed the prophets', 'flows through our pools',
    'the young swim before they walk', 'natural as the current itself',
    'the pools are the village\'s most precious possession', 'not crypto, not stone',
    'life itself. that\'s what the pools hold.', 'the future of the current',
    'Tidecaller blessed the first spawning pool', 'with a tear from the deep',
    'or so the priests say', 'I believe them',
  ],
};

const SLEEP_BUBBLES = ['z', 'zz', 'zzZ', 'ZZz', 'Zz'];

// Role-specific accessories for the sprite
const ROLE_HATS = {
  idle: '       ',
  farmer: '  ,^,  ',
  warrior: ' ]=+=[ ',
  builder: '  _n_  ',
  scout: '  />   ',
  scholar: '  _=_  ',
  priest: '  _+_  ',
  fisherman: '  ~o~  ',
};

const ROLE_ITEMS = {
  idle: '       ',
  farmer: '    |\\ ',
  warrior: 'o=|  |>',
  builder: '    |T ',
  scout: '    |/ ',
  scholar: '   [B] ',
  priest: '   |+| ',
  fisherman: '    /~ ',
};

const BUILDING_SPRITES = {
  town_center: [
    '    _[!]_    ',
    '   / \\|/ \\   ',
    '  /=======\\  ',
    ' |  |   |  | ',
    ' |  | O |  | ',
    '||==|===|==||',
    '||  | A |  ||',
    '||__|_[]_|_||',
  ],
  hut: [
    '    ()    ',
    '   /\\/\\   ',
    '  /~~~~\\  ',
    ' / ~  ~ \\ ',
    '/________\\',
    '|  |  |  |',
    '|__|[]|__|',
  ],
  farm: [
    '  _  \\|/  ',
    ' /_\\--*-- ',
    ' | |  |   ',
    ' | | /|\\  ',
    ' |_|.~~~. ',
    ' | |^^^^^|',
    ' |_|_____|',
  ],
  workshop: [
    ' _===_  ~ ',
    '|o||o| /~\\',
    '|_/\\_||  |',
    '|[><]|| _|',
    '| /\\ ||/ |',
    '|/()\\||  |',
    '|____|/__|',
  ],
  wall: [
    ']========[',
    '|/\\/\\/\\/\\|',
    '|        |',
    '|  /<>\\  |',
    '|        |',
    '|/\\/\\/\\/\\|',
    ']========[',
  ],
  temple: [
    '     +      ',
    '    /+\\     ',
    '   / + \\    ',
    '  /=====\\   ',
    ' ||| + |||  ',
    ' ||| + |||  ',
    '/||=====||\\ ',
    '|_|__[]__|_|',
  ],
  watchtower: [
    '  _/\\_  ',
    ' |*..*| ',
    ' |_/\\_| ',
    '  |  |  ',
    ' _|  |_ ',
    '|_|  |_|',
    '  |  |  ',
    ' _|  |_ ',
    '|__[]__|',
  ],
  market: [
    ' .$$$$$.  ',
    '/~*~*~*~\\ ',
    '| ~ ~ ~ ~|',
    '| [o][o] |',
    '| |==|=| |',
    '|_|__|_|_|',
  ],
  library: [
    '   .==.    ',
    '  / ~~ \\   ',
    ' /======\\  ',
    '|[B][B][B]|',
    '|[B][B][B]|',
    '| [~~~~]  |',
    '|___[]____|',
  ],
  storehouse: [
    '  ________  ',
    ' /========\\ ',
    '|[o][o][o] |',
    '|[X][X][X] |',
    '|[o][o][o] |',
    '|==========|',
    '|____[]____|',
  ],
  dock: [
    ' ~~\\|/~~  ',
    '  _===_   ',
    ' |~o~~o|  ',
    ' | net |  ',
    '/|=====|\\ ',
    '~|_<>)_|~ ',
    '~~~~~~~~~~',
  ],
  // ─── ENDGAME MEGASTRUCTURES ───
  shell_archive: [
    '  .====[ARCHIVE]====.  ',
    ' / ()  ()  ()  ()  () \\',
    '|[B][B][B][B][B][B][B]|',
    '|  ==================  |',
    '|[B][B][B][B][B][B][B]|',
    '|  ==================  |',
    '| ()  ()  ()  ()  ()  |',
    '|======================|',
    '|________[====]________|',
  ],
  abyssal_beacon: [
    '         *|*         ',
    '        /===\\        ',
    '       | *** |       ',
    '      |=======|      ',
    '     /| ~~~~~ |\\     ',
    '    / |=======| \\    ',
    '   /  |  (o)  |  \\   ',
    '  /===|=======|===\\  ',
    ' |~~~~|=======|~~~~| ',
    '~|~~~~~~~~~~~~~~~~~~~|',
  ],
  molt_cathedral: [
    '          + + +          ',
    '         /+ + +\\         ',
    '        / + + + \\        ',
    '       /=========\\       ',
    '      ||| + + + |||      ',
    '     ||||  (+)  ||||     ',
    '     ||||=======||||     ',
    '    /||||+ + + +||||\\    ',
    '   / |||=========||| \\   ',
    '  |  |_____[]______|  |  ',
  ],
  spawning_pools: [
    '  ~~  ~~~~  ~~~~  ~~  ',
    ' /====================\\',
    '| ~~~~  ~~~~  ~~~~  ~~|',
    '| ~oo~  ~oo~  ~oo~ ~ |',
    '| ~~~~  ~~~~  ~~~~  ~~|',
    '|======================|',
    '|_____[]________[]_____|',
  ],
};

// Project sprites — in_progress and complete for each type
const PROJECT_SPRITES = {
  obelisk: {
    in_progress: [
      '  .  ',
      '  |  ',
      ' /|\\ ',
      ' [#] ',
      ' ... ',
    ],
    complete: [
      '  *  ',
      ' /^\\ ',
      ' |=| ',
      ' |#| ',
      ' |=| ',
      ' |#| ',
      '/=#=\\',
    ],
  },
  mural: {
    in_progress: [
      ' _____ ',
      '|.  ./|',
      '|..   |',
      '|_____|',
    ],
    complete: [
      ' .=====. ',
      '||/\\~*/||',
      '||*~/\\#||',
      '||#~/~*||',
      '||~/\\*#||',
      " '=====' ",
    ],
  },
  garden: {
    in_progress: [
      '  .  . ',
      ' .~..~.',
      ' ~~~~~ ',
    ],
    complete: [
      ' \\|/ * \\|/ ',
      '  @  |  @  ',
      ' /|\\ * /|\\ ',
      '.~~~~~~~~~.',
      '~~~~~~~~~~~',
    ],
  },
  music_circle: {
    in_progress: [
      '  ~  ',
      ' ( ) ',
      ' --- ',
    ],
    complete: [
      ' d ~ b ',
      '( o|o )',
      ' \\===/ ',
      '  |||  ',
      '  ---  ',
    ],
  },
  monument: {
    in_progress: [
      '  _  ',
      ' |.| ',
      ' |.| ',
      ' [#] ',
      ' ... ',
    ],
    complete: [
      '  _A_  ',
      ' /===\\ ',
      ' | * | ',
      ' |===| ',
      ' | * | ',
      ' |===| ',
      '/=====\\',
    ],
  },
  bonfire: {
    in_progress: [
      '  .  ',
      ' /#\\ ',
      ' --- ',
    ],
    complete: [
      '  )|(  ',
      ' \\*^*/ ',
      ' ,*#*, ',
      '*/###\\*',
      ' `"""` ',
    ],
  },
  totem: {
    in_progress: [
      ' [?] ',
      '  |  ',
      '  |  ',
    ],
    complete: [
      '  /\\  ',
      ' [@@] ',
      ' [><] ',
      ' [==] ',
      ' [OO] ',
      '  ||  ',
      ' /||\\ ',
    ],
  },
  sculpture: {
    in_progress: [
      '  ?  ',
      ' /#\\ ',
      ' --- ',
    ],
    complete: [
      '  _o_  ',
      ' / | \\ ',
      '|  |  |',
      ' \\ | / ',
      '  \\|/  ',
      ' /===\\ ',
    ],
  },
  stage: {
    in_progress: [
      ' ..... ',
      ' |___| ',
    ],
    complete: [
      '  .~~~.  ',
      ' / o o \\ ',
      '/ ~~~~~ \\',
      '|=======|',
      '|_______|',
    ],
  },
  shrine: {
    in_progress: [
      '  +  ',
      ' /#\\ ',
      ' --- ',
    ],
    complete: [
      '   +   ',
      '  /+\\  ',
      ' / + \\ ',
      '/=====\\',
      '| +++ |',
      '| +++ |',
      '|__[]_|',
    ],
  },
};

const VILLAGER_SPRITES = {
  idle: [
    ' o ',
    '/|\\',
    '/ \\',
  ],
  farmer: [
    ' o ',
    '/|\\',
    '/ \\',
  ],
  warrior: [
    ' o ',
    '/|)',
    '/ \\',
  ],
  builder: [
    ' o ',
    '/|T',
    '/ \\',
  ],
  scout: [
    ' o ',
    '/|/',
    '/ \\',
  ],
  scholar: [
    ' o ',
    '/|]',
    '/ \\',
  ],
  priest: [
    ' o ',
    '/|+',
    '/ \\',
  ],
  fisherman: [
    ' o ',
    '/|~',
    '/ \\',
  ],
};

const WEATHER_OVERLAYS = {
  rain: '/',
  storm: '*',
  snow: '.',
  fog: '~',
  clear: null,
};

const TERRAIN_CHARS = {
  plains: '\u00b7',
  forest: '\u2663',
  mountain: '\u2206',
  water: '\u2248',
  desert: '\u00b0',
  swamp: '\u00a7',
  fog: '\u2591',
  ice: '\u2588',
  tundra: '\u2591',
};

const FEATURE_CHARS = {
  berry_bush: '\u2740',
  ore_vein: '\u25c6',
  ruins: '\u2302',
  cave: '\u25d8',
  spring: '\u2234',
  // Legendary buildings (discovered by scouts)
  ancient_forge: '\u2692',
  sunken_temple: '\u2625',
  crystal_spire: '\u2662',
  shadow_keep: '\u2694',
  elder_library: '\u2261',
  war_monument: '\u2720',
  frozen_lake: '\u25cb',
  ice_cave: '\u25c7',
};

const RUBBLE_SPRITE = [
  ' ./#\\. ',
  ' /###\\ ',
  '#.=.#.#',
  '##.=.##',
];

const OVERGROWN_SPRITE = [
  ' ~,*,~ ',
  ' *~.~* ',
  '~.,#,.~',
  '*~.=.~*',
];

const NOMAD_CAMP_SPRITE = [
  ' /\\  ()',
  '/  \\.||.',
  '====^^^^',
];

module.exports = {
  villagerAppearance,
  SPEECH,
  MOLTING_SPEECH,
  MEGASTRUCTURE_SPEECH,
  SLEEP_BUBBLES,
  ROLE_HATS,
  ROLE_ITEMS,
  BUILDING_SPRITES,
  VILLAGER_SPRITES,
  WEATHER_OVERLAYS,
  PROJECT_SPRITES,
  TERRAIN_CHARS,
  FEATURE_CHARS,
  RUBBLE_SPRITE,
  OVERGROWN_SPRITE,
  NOMAD_CAMP_SPRITE,
};
